"""
app/api/v1/forms.py
===================
API router for Google Forms and Form Schema operations.

Routes:
  - POST /api/v1/forms/generate-schema      → LLM prompt → FormSchema JSON
  - POST /api/v1/forms/prompt-generate      → LLM prompt → creates real Google Form with questions
  - POST /api/v1/forms/create               → Create blank Google Form
  - GET  /api/v1/forms/{formId}             → Get Google Form metadata
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Cookie, Header, HTTPException, status
from pydantic import BaseModel, Field

from app.auth.service import google_auth_service
from app.forms.schemas import FormSchema
from app.google.forms import GoogleFormsError, google_forms_service
from app.llm.exceptions import LLMError
from app.llm.factory import get_llm_provider

logger = logging.getLogger(__name__)

router = APIRouter(prefix="", tags=["Google Forms"])


# ======================================================================
# Request / Response Schemas
# ======================================================================

class GenerateSchemaRequest(BaseModel):
    prompt: str = Field(..., min_length=1, description="Natural language prompt describing the form to create")


class PromptGenerateRequest(BaseModel):
    prompt: str = Field(..., min_length=1, description="Natural language prompt describing the Google Form to create or modify")
    provider: str | None = Field(default=None, description="LLM provider override (default: gemini)")
    current_form_id: str | None = Field(default=None, description="ID of existing Google Form to modify, if any")
    current_schema: FormSchema | None = Field(default=None, description="Current FormSchema if modifying an existing form")


class PromptGenerateResponse(BaseModel):
    formId: str = Field(..., description="Google Form unique identifier")
    title: str = Field(..., description="Form title generated by AI")
    description: str = Field(default="", description="Form description")
    editUrl: str = Field(..., description="Google Forms edit URL for form owner")
    responderUrl: str = Field(..., description="Public shareable URL for respondents")
    createdTime: str = Field(..., description="ISO 8601 creation timestamp")
    questionCount: int = Field(default=0, description="Number of questions added to the form")
    form_schema: FormSchema = Field(..., description="Generated form schema from AI")


class FormCreateRequest(BaseModel):
    title: str = Field(default="Untitled Form", description="Title for the new Google Form")


class FormCreateResponse(BaseModel):
    formId: str = Field(..., description="Google Form unique identifier")
    title: str = Field(..., description="Form title")
    editUrl: str = Field(..., description="Google Forms edit URL for form owner")
    responderUrl: str = Field(..., description="Public shareable URL for respondents")
    createdTime: str = Field(..., description="ISO 8601 creation timestamp")


class FormDetailsResponse(BaseModel):
    formId: str = Field(..., description="Google Form unique identifier")
    title: str = Field(..., description="Form title")
    description: str = Field("", description="Form description")
    revisionId: str = Field("", description="Form revision identifier")
    responderUrl: str = Field(..., description="Public shareable URL")
    editUrl: str = Field(..., description="Google Forms edit URL")


# ======================================================================
# Helpers
# ======================================================================

def _extract_access_token(session_token: str | None, authorization: str | None) -> str:
    token = session_token
    if not token and authorization and authorization.startswith("Bearer "):
        token = authorization.split("Bearer ", 1)[1].strip()

    if not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required. Please sign in with Google.",
        )

    access_token = google_auth_service.get_access_token_from_session(token)
    if not access_token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Valid Google OAuth access token not found in session. Please sign in again.",
        )
    return access_token


# ======================================================================
# Endpoints
# ======================================================================

@router.post(
    "/generate-schema",
    response_model=FormSchema,
    summary="Generate Form Schema from Prompt",
    description="Converts natural language description into a validated, structured FormSchema JSON.",
)
async def generate_form_schema(
    payload: GenerateSchemaRequest,
    provider: str | None = None,
) -> FormSchema:
    """
    Convert prompt into a validated FormSchema JSON object.
    Does NOT call Google Forms API or create external forms.
    """
    if not payload.prompt or not payload.prompt.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Prompt text cannot be empty.",
        )

    try:
        provider_instance = get_llm_provider(provider_name=provider)
        form_schema = await provider_instance.generate_form_schema(payload.prompt)
        return form_schema
    except LLMError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)
    except Exception as exc:
        logger.exception("Unexpected error generating form schema: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate form schema: {str(exc)}",
        )


@router.post(
    "/prompt-generate",
    response_model=PromptGenerateResponse,
    summary="AI Prompt → Create Full Google Form",
    description=(
        "Takes a natural language prompt, uses AI to design the complete form schema, "
        "then creates a real Google Form in the user's Google account with all questions populated. "
        "This is the main AI-powered form creation endpoint."
    ),
)
async def prompt_generate_form(
    payload: PromptGenerateRequest,
    session_token: str | None = Cookie(default=None),
    authorization: str | None = Header(default=None),
) -> PromptGenerateResponse:
    """
    Full pipeline: prompt → AI schema → create Google Form with all questions.
    """
    if not payload.prompt or not payload.prompt.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Prompt text cannot be empty.",
        )

    # Step 1: Validate auth
    access_token = _extract_access_token(session_token, authorization)

    # Step 2: Generate FormSchema from AI
    try:
        provider_instance = get_llm_provider(provider_name=payload.provider)
        form_schema = await provider_instance.generate_form_schema(
            payload.prompt, current_schema=payload.current_schema
        )
    except LLMError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)
    except Exception as exc:
        logger.exception("Unexpected error generating form schema from prompt: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"AI failed to generate form schema: {str(exc)}",
        )

    # Step 3: Create or update Google Form
    try:
        if payload.current_form_id:
            result = await google_forms_service.update_form_from_schema(
                access_token=access_token,
                form_id=payload.current_form_id,
                form_schema=form_schema,
            )
        else:
            result = await google_forms_service.create_form_from_schema(
                access_token=access_token,
                form_schema=form_schema,
            )
    except GoogleFormsError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)
    except Exception as exc:
        logger.exception("Unexpected error processing Google Form from schema: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error while processing Google Form.",
        )

    return PromptGenerateResponse(
        formId=result["formId"],
        title=result["title"],
        description=result.get("description", ""),
        editUrl=result["editUrl"],
        responderUrl=result["responderUrl"],
        createdTime=result["createdTime"],
        questionCount=result.get("questionCount", 0),
        form_schema=form_schema,
    )


@router.post(
    "/create",
    response_model=FormCreateResponse,
    summary="Create Blank Google Form",
    description="Creates a new blank Google Form in the authenticated user's Google Workspace account.",
)
async def create_form(
    payload: FormCreateRequest | None = None,
    session_token: str | None = Cookie(default=None),
    authorization: str | None = Header(default=None),
) -> FormCreateResponse:
    """
    Create a new blank Google Form.
    """
    access_token = _extract_access_token(session_token, authorization)
    title = payload.title if payload and payload.title else "Untitled Form"

    try:
        result = await google_forms_service.create_blank_form(access_token=access_token, title=title)
        return FormCreateResponse(**result)
    except GoogleFormsError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)
    except Exception as exc:
        logger.exception("Unexpected error during Google Form creation: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error creating Google Form.",
        )


@router.get(
    "/{formId}",
    response_model=FormDetailsResponse,
    summary="Get Google Form Details",
    description="Retrieves metadata for an existing Google Form by ID.",
)
async def get_form(
    formId: str,
    session_token: str | None = Cookie(default=None),
    authorization: str | None = Header(default=None),
) -> FormDetailsResponse:
    """
    Get Google Form metadata.
    """
    access_token = _extract_access_token(session_token, authorization)
    try:
        result = await google_forms_service.get_form_details(access_token=access_token, form_id=formId)
        return FormDetailsResponse(**result)
    except GoogleFormsError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)
    except Exception as exc:
        logger.exception("Unexpected error retrieving Google Form: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal server error retrieving Google Form details.",
        )
